// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.ParticipantController.Edit(System.Guid)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.ParticipantController.Edit(System.Guid)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.JuryController.Assessment(System.Guid,Rauthor.Models.ParticipantAssessment)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.AccountController.Register(Rauthor.Models.Api.Login)~Rauthor.Models.Api.LoginResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.AccountController.Post(Rauthor.Models.Api.Login)~Rauthor.Models.Api.LoginResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.AccountController.Login(Rauthor.Models.Api.Login)~Rauthor.Models.Api.LoginResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.CompetitionController.Put(System.Guid,Rauthor.Models.Competition)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.CompetitionController.Post(Rauthor.Models.Competition)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.AccountController.Post(Rauthor.Models.Api.Login)~Rauthor.Models.Api.LoginResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.AccountController.Register(Rauthor.ViewModels.RegistrationModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.AccountController.Register(Rauthor.ViewModels.RegistrationModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Rauthor.Controllers.Api.CompetitionController.Post(Rauthor.Models.Competition)~Microsoft.AspNetCore.Mvc.IActionResult")]
